<?php 

use PackageDelivery\Models\Employee;
/** @var string $content */ 

/** @var ?Employee $user*/
$user = $_SESSION["user"] ?? null;
?>

<!DOCTYPE html>
<html lang="fr" data-theme="corporate">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Packet Delivery</title>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@5" rel="stylesheet" type="text/css" />
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link href="https://cdn.jsdelivr.net/npm/daisyui@5/themes.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
    integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
    crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
    integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
    crossorigin=""></script>
</head>

<body class="flex flex-col h-screen">
    <header>
        <div class="navbar bg-base-100 shadow-sm">
            <div class="navbar-start">
                <span class="text-xl font-bold">
                    <?= htmlspecialchars($user != null ? "Welcome {$user->firstName} {$user->lastName}" : "Packet Delivery"); ?>
                </span>
            </div>
            <div class="navbar-center">
                <a class="btn btn-ghost h-12 w-12 p-0" href="/">
                    <img class="h-full" src="/img/logo.png" alt="">
                </a>
            </div>
            <div class="navbar-end">
                <form action="/logout" method="post">
                    <button type="submit" class="btn btn-ghost btn-error p-0">
                        <i class="bi bi-power text-4xl"></i>
                    </button>
                </form>
            </div>
        </div>
    </header>
        <?= $content ?>
    <footer class="flex justify-center bg-neutral text-neutral-content p-10">
        <h1 class="text-2xl font-bold">Packet Delivery &copy; 2026</h1>
    </footer>
</body>
<script>
    function applyTheme() {
        const isDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        document.documentElement.setAttribute('data-theme', isDark ? 'dark' : 'light');
    }
    //applyTheme();

    //window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', applyTheme);
</script>

</html>