<?php
use PackageDelivery\Schemas\Login;

use function PackageDelivery\Components\ErrorMessages;

/** @var Login $data */
/** @var array<string, mixed> $errors */

?>
<main class="flex-1 flex justify-center items-center">
    <form method="post" action="/login" class="card bg-base-100 w-full max-w-sm shrink-0 shadow-2xl">
        <div class="card-body">
            <h1 class="font-bold text-2xl text-center">Login</h1>
            <fieldset class="fieldset">

                <label class="label">Email</label>
                <label class="input">
                    <i class="bi bi-envelope-at opacity-50"></i>
                    <input type="text" name="email" class="grow" placeholder="Email" value="<?= $data->email ?>" />
                </label>
                <? ErrorMessages($errors, "email") ?>

                <label class="label">Password</label>
                <label class="input">
                    <i class="bi bi-key text-xl opacity-50"></i>
                    <input type="password" name="password" placeholder="Password" value="<?= $data->password ?>" />
                </label>
                <? ErrorMessages($errors, "password") ?>

                <button class="btn btn-primary mt-4">Login</button>
            </fieldset>
        </div>
    </form>
</main>